---
application:
  name: "arb-react"
  project: "arb-react"
  organization: "QoveryCommunity"
  storage:
  - name: "images"
    size: "10"
    type: "ssd"
    mount_point: "/mnt/images"
routers:
- name: "main-arb-react"
  routes:
  - application_name: "arb-react"
    paths:
    - "/*"
